name: 'Grant Action'
description: 'Executes the grant license compliance program to list discovered licenses as CSV'
inputs:
  input:
    description: 'Input of SBOM or Docker image that will generate a license manifest'
    required: true
outputs:
  license_list:
    description: 'csv of provided inputs'
runs:
  using: 'node20'
  main: 'dist/index.js'
