name: Publish License Data

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  get-licenses:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-for-analysis: ["debian:latest", "alpine:latest", "python:latest"]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Create shared directory
        run: |
          mkdir -p artifacts

      - uses: anchore/sbom-action@v0
        name: Generate image SBOM
        with:
          image: ${{ matrix.image-for-analysis }}
          format: json
          upload-artifact: false
          upload-release-assets: false
          output-file: 'artifacts/image.sbom'

      - name: Generate license report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./
        with:
          input: "artifacts/image.sbom"

      - name: Send output to file
        run: echo ${{steps.generate_license_report.outputs.license_list}} > output.csv

      - name: Convert CSV to Array and Export to JSON
        id: convert_csv
        run: python convert_csv.py

      - uses: jroehl/gsheet.action@release
        with:
          spreadsheetId: ${{ secrets.SPREADSHEET_ID }}
          commands: |
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": ${{ matrix.image-for-analysis }} }},
              { "command": "updateData", "args": { "data": ${{ needs.convert.outputs.json_data}} }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
