name: Publish License Data

on:
  push:
    branches:
      - main

jobs:
  get-licenses:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-for-analysis: ["debian:latest", "alpine:latest", "python:latest"]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Create shared directory
        run: |
          mkdir -p artifacts
      - uses: anchore/sbom-action@v0
        name: Generate image SBOM
        with:
          image: ${{ matrix.image-for-analysis }}
          format: json
          upload-artifact: false
          upload-release-assets: false
          output-file: 'artifacts/image.sbom'
      - name: Generate license report from sbom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./
        with:
          input: "artifacts/image.sbom"

      - uses: jroehl/gsheet.action@release
        with:
          spreadsheetId: ${{ secrets.SPREADSHEET_ID }}
          commands: |
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "<worksheetTitle>" }},
              { "command": "updateData", "args": { "data": [["A1", "A2", "A3"]] }},
              { "command": "getData", "args": { "range": "'<worksheetTitle>'!A2:B3" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
